language: python
sudo: required
dist: trusty
install:
- cd 2019
- bash devtools/install/install.sh
- export PATH="`pwd`/anaconda/bin:$PATH"
- source activate aoc2019
- python setup.py install
script:
- cd 2019
- nosetests -q aoc2019/* --nologcapture

